### ISSUE TITLE
关于.Tag文件

### ISSUE THREAD

**Issue by PengKunPROO** [cv-rits/COARSE3D#1]
你好，感谢你们的工作，非常优秀！也感谢你们的开源让我们得以使用这么好的项目。我在使用你们的项目做点云语义分割时发现在semanticPOSS里有tag文件，不清楚其具体含义和来源。所以如果我使用你们的预训练模型来测试自己的数据时，可否只有.label和.bin的序列文件就能跑呢？
感谢您的回复，谢谢！

**Comment by iris0329** [comment]
Hello, thanks for your interest in our work. For `tag` file, plz refer to the [official web of SemanticPOSS](http://www.poss.pku.edu.cn/semanticposs.html).
Thanks.
