### ISSUE TITLE
train

### ISSUE THREAD

**Issue by MarcusnHuang** [cv-rits/COARSE3D#2]
Hello, during the process of reproducing Coarse3d and preparing training semantic_poss data, the following problem occurred. May I ask what caused this problem?

 File "../../pc_processor/models/salsanext_proto.py", line 436, in forward
    assert h % 16 == 0, w % 16 == 0
AssertionError: False

**Comment by mxzel** [comment]
Same error. For SemanticPOSS dataset, the results of h and w are as follows:
```python
h = 64
w = 2048

h = h + 8
w = w + 8
```
After that, the assertion `h % 16 == 0, w % 16 == 0` seems always failed.

**Comment by iris0329** [comment]
Hi @mxzel @MarcusnHuang, Thank you for your interest in our work. I'm sorry to say that I'm currently swamped and won't be able to review this code. Would you be willing to take a look at the [CENet](https://github.com/huixiancheng/CENet) instead? It comes with the SemanticPOSS data loader included. Thank you for your understanding and support.
